param(
    #The .db file generated by Huawei Backup that you want to extract.
    [Parameter(Mandatory)][string]$BackupFile,
    #The directory to extract the contents of the backup into.
    [Parameter(Mandatory)][string]$ExtractDir
)

if (!(Get-Module PSSQLite))
{
    Import-Module PSSQLite
}

#The apk_file_info table contains the file and directory names. Directories all have a file_index of -1, files just have a sequential index number.

$file_structure = Invoke-SqliteQuery -DataSource $BackupFile -Query "SELECT * FROM apk_file_info"

#Create directory structure.
$file_structure | %{
    if ($_.file_index -eq -1)
    {
        $dirpath = Join-Path $ExtractDir $_.file_path
        if (!(Test-Path $dirpath))
        {
            New-Item -ItemType Directory -Path $dirpath
        }
    }
}

